# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =      -std=c++14 -DHIGH_PREC   -I/home/deepmdroot/include -I/home/Paddle/build/paddle_inference_install_dir/paddle/include  -std=c++14 -DHIGH_PREC   -I/home/deepmdroot/include -I/home/Paddle/build/paddle_inference_install_dir/paddle/include
PKG_PATH =     -L/home/deepmdroot/lib -L/home/Paddle/build/paddle_inference_install_dir/paddle/lib -L/home/paddle-deepmd/source/build/  -L/home/deepmdroot/lib -L/home/Paddle/build/paddle_inference_install_dir/paddle/lib -L/home/paddle-deepmd/source/build/
PKG_LIB =     -Wl,--no-as-needed -ldeepmd_cc -ldeepmd -Wl,-rpath=/home/deepmdroot/lib -Wl,--no-as-needed -ldeepmd_cc -ldeepmd -Wl,-rpath=/home/deepmdroot/lib   -Wl,--no-as-needed -ldeepmd_cc -ldeepmd -Wl,-rpath=/home/deepmdroot/lib  -lpd_infer_custom_op
PKG_CPP_DEPENDS = 
PKG_LINK_DEPENDS = 

PKG_SYSINC =  
PKG_SYSLIB =  
PKG_SYSPATH = 
